### ISSUE TITLE
reuseport.Dialer missing

### ISSUE THREAD

**Issue by alexio777** [gobs/httpclient#2]
Hello

Dialer struct is missing in package github.com/jbenet/go-reuseport

> github.com/gobs/httpclient/httpclient.go:419:14: undefined: reuseport.Dialer

**Comment by chilic** [comment]
Looks like this issues fixed by https://github.com/gobs/httpclient/commit/bc9e0b12b2cba9dded5883505eb9bb45f68796f1

Thanks.
